eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    #hostname: localhost
spring:
  application:
    name: customer
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      username: admin
      password: admin@123
  rabbitmq:
    host: 34.87.180.247
    username: admin
    password: password
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: "*"